import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fireball</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background flex min-h-screen bg-black">
        <div className="container mx-auto max-w-2xl">
          <Header />
        </div>
      </main>
    </>
  );
};

export default Home;
